# Generated by Django 4.2.15 on 2026-09-11 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_subscription_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('provider', models.CharField(default='tranzila', editable=False, max_length=20)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('product', models.CharField(choices=[('coins', 'Coins'), ('subscription', 'Subscription')], max_length=20)),
                ('tier', models.CharField(blank=True, max_length=16)),
                ('coin_quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('ILS', 'ILS'), ('USD', 'USD'), ('EUR', 'EUR')], default='ILS', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], default='draft', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checkouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='billing.checkoutrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='checkoutrequest',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='checkout_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='checkoutrequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('coin_quantity__gt', 0), ('product', 'coins'), ('tier', '')), models.Q(('coin_quantity', 0), ('product', 'subscription'), ('tier__in', ['GOLD', 'PREMIUM', 'VIP'])), _connector='OR'), name='checkout_product_units'),
        ),
    ]
