# Generated by Django 4.2.15 on 2026-09-11 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_checkoutrequest_checkoutevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('subscription', 'Subscription'), ('coins', 'Coins')], max_length=16)),
                ('tier', models.CharField(blank=True, max_length=16)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('ILS', 'ILS'), ('USD', 'USD'), ('EUR', 'EUR')], default='ILS', max_length=3)),
                ('coin_quantity', models.PositiveIntegerField(default=0)),
                ('period_months', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='product_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='StoreProductAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='billing.storeproduct')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'subscription')), fields=('tier',), name='store_one_product_per_tier'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='store_nonnegative_price'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('coin_quantity__gt', 0), ('kind', 'coins'), ('period_months', 0), ('tier', '')), models.Q(('coin_quantity', 0), ('kind', 'subscription'), ('period_months__in', [1, 3, 6, 12]), ('tier__in', ['FREE', 'GOLD', 'PREMIUM', 'VIP'])), _connector='OR'), name='store_valid_product'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(check=models.Q(('active', False), models.Q(('price', 0), ('tier', 'FREE')), ('price__gt', 0), _connector='OR'), name='store_active_price'),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='catalog_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.storeproduct'),
        ),
    ]
