# Generated by Django 4.2.15 on 2026-09-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_entry_fee_wallettransaction_and_more'),
        ('billing', '0005_seed_membership_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrequest',
            name='checkout_session',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='provider_terminal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='provider_transaction_index',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.wallettransaction'),
        ),
    ]
