# Generated by Django 4.2.15 on 2026-09-12 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_checkoutrequest_checkout_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranzilaRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('terminal', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=10)),
                ('status', models.CharField(default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('date_from', models.DateField(null=True)),
                ('date_to', models.DateField(null=True)),
                ('checked', models.PositiveIntegerField(default=0)),
                ('recovered', models.PositiveIntegerField(default=0)),
                ('issues', models.PositiveIntegerField(default=0)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_payments', 'Manage payment reconciliation and refund tracking')],
            },
        ),
        migrations.CreateModel(
            name='TranzilaIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=10)),
                ('transaction_index', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('resolution_reference', models.CharField(blank=True, max_length=100)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.checkoutrequest')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('provider_reference', models.CharField(max_length=100)),
                ('provider_terminal', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjustment_reference', models.CharField(blank=True, max_length=100)),
                ('adjusted_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_records', to='billing.checkoutrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tranzilarun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('terminal', 'environment', 'kind'), name='tranzila_one_running_operation'),
        ),
        migrations.AddConstraint(
            model_name='tranzilaissue',
            constraint=models.UniqueConstraint(fields=('terminal', 'environment', 'transaction_index', 'code'), name='tranzila_issue_unique'),
        ),
        migrations.AddConstraint(
            model_name='checkoutrefund',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='checkout_refund_positive'),
        ),
        migrations.AddConstraint(
            model_name='checkoutrefund',
            constraint=models.UniqueConstraint(fields=('provider_terminal', 'environment', 'provider_reference'), name='checkout_refund_provider_unique'),
        ),
    ]
