# Generated by Django 4.2.15 on 2026-09-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_payment_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrequest',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
