"""
Django settings for tournaments project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


def load_local_env(path):
    """Load simple KEY=VALUE pairs for local development without overriding real env vars."""
    if not path.is_file():
        return

    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


def env_list(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


# `.env` lives beside the repository's README, not inside the Django package.
# Deployment environments can still provide real environment variables, which always take priority.
load_local_env(BASE_DIR.parent / '.env')

# Opt-in Web Push. The private key belongs only on the server.
WEB_PUSH_PUBLIC_KEY = os.environ.get('WEB_PUSH_PUBLIC_KEY', '')
WEB_PUSH_PRIVATE_KEY = os.environ.get('WEB_PUSH_PRIVATE_KEY', '')
WEB_PUSH_SUBJECT = os.environ.get('WEB_PUSH_SUBJECT', '')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polymorphic',
    'crispy_forms',
    'crispy_bootstrap4',
    'capture_tag',
    'channels',
    'tournaments',
    'frontend',
    'gamelink',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tournaments.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tournaments.wsgi.application'
ASGI_APPLICATION = 'tournaments.asgi.application'

REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CHANNEL_LAYER_BACKEND = os.environ.get('CHANNEL_LAYER_BACKEND')
if CHANNEL_LAYER_BACKEND is None:
    settings_module = os.environ.get('DJANGO_SETTINGS_MODULE', '')
    CHANNEL_LAYER_BACKEND = 'memory' if settings_module.endswith('.development') else 'redis'
CHANNEL_LAYER_BACKEND = CHANNEL_LAYER_BACKEND.lower()
if CHANNEL_LAYER_BACKEND == 'redis':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'


# Game link — see tournaments-backgammon-messaging.md
#
# The feature ships switched off. Enabling it is a deployment step, and rolling it back is a matter
# of switching it off again: the button disappears and manual scoring carries on untouched.
# Secrets come from the environment only, are never `SECRET_KEY`, and the two channels never share
# one. `gamelink.checks` refuses to boot on a weak configuration outside DEBUG.

GAMELINK_ENABLED        = os.environ.get('GAMELINK_ENABLED', '0') == '1'
GAMELINK_ISSUER         = 'tournaments'
GAMELINK_AUDIENCE       = 'backgammon'
GAMELINK_BACKGAMMON_URL = os.environ.get('GAMELINK_BACKGAMMON_URL', '')  # https://…, no path
GAMELINK_TICKET_SECRET  = os.environ.get('GAMELINK_TICKET_SECRET', '')
GAMELINK_RESULT_SECRETS = [s for s in os.environ.get('GAMELINK_RESULT_SECRETS', '').split(',') if s]
GAMELINK_COMMAND_SECRET = os.environ.get('GAMELINK_COMMAND_SECRET', '')
GAMELINK_TICKET_TTL     = 120        # seconds a minted ticket stays redeemable
GAMELINK_LINK_TTL       = 7200       # seconds a game link stays open before it is refreshed
GAMELINK_CLOCK_SKEW     = 300        # seconds of tolerance on an inbound result timestamp
GAMELINK_MAX_BODY       = 64 * 1024  # bytes; larger result bodies are rejected unread
GAMELINK_TARGET_POINTS  = 1          # match length, in points; decided (plan §9, decision 1)

# Set the canonical public website URL, never construct email links from the Host header.
ACCOUNT_FRONTEND_URL = os.environ.get('ACCOUNT_FRONTEND_URL', 'http://localhost:5174/tournaments')
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
PASSWORD_RESET_TIMEOUT = 3600
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1') == '1'
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'accounts@localhost')

# Sandbox subscriptions. No real-money endpoint is supported by this integration.
BILLING_ENABLED = os.environ.get('BILLING_ENABLED', '0') == '1'
# Tranzila preparation is independent of the legacy PayPal sandbox switch.
# "test" identifies a merchant test terminal; it does not select a sandbox URL.
TRANZILA_ENABLED = os.environ.get('TRANZILA_ENABLED', '0') == '1'
TRANZILA_ENVIRONMENT = os.environ.get('TRANZILA_ENVIRONMENT', 'test')
TRANZILA_TERMINAL = os.environ.get('TRANZILA_TERMINAL', '')
TRANZILA_APP_KEY = os.environ.get('TRANZILA_APP_KEY', '')
TRANZILA_APP_SECRET = os.environ.get('TRANZILA_APP_SECRET', '')
TRANZILA_RETURN_URL = os.environ.get('TRANZILA_RETURN_URL', '')
TRANZILA_NOTIFY_URL = os.environ.get('TRANZILA_NOTIFY_URL', '')
TRANZILA_REPORT_MAPPING_CONFIRMED = os.environ.get('TRANZILA_REPORT_MAPPING_CONFIRMED', '0') == '1'
TRANZILA_APPROVED_TRANSTATUS = os.environ.get('TRANZILA_APPROVED_TRANSTATUS', '')
PAYPAL_ENVIRONMENT = os.environ.get('PAYPAL_ENVIRONMENT', 'sandbox')
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.environ.get('PAYPAL_CLIENT_SECRET', '')
PAYPAL_WEBHOOK_ID = os.environ.get('PAYPAL_WEBHOOK_ID', '')
PAYPAL_PLAN_ID = os.environ.get('PAYPAL_PLAN_ID', '')
# Explicit sandbox provider-plan mapping. PAYPAL_PLAN_ID is an optional default
# and must match one of these IDs; it never assigns a tier on its own.
PAYPAL_GOLD_PLAN_ID = os.environ.get('PAYPAL_GOLD_PLAN_ID', '')
PAYPAL_PREMIUM_PLAN_ID = os.environ.get('PAYPAL_PREMIUM_PLAN_ID', '')
PAYPAL_VIP_PLAN_ID = os.environ.get('PAYPAL_VIP_PLAN_ID', '')
BILLING_RETURN_URL = os.environ.get('BILLING_RETURN_URL', 'http://localhost:5173/tournaments/subscription')
