# Generated by Django 4.2.15 on 2026-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_push_worker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepushdelivery',
            name='kind',
            field=models.CharField(choices=[('guest_joined', 'Guest joined'), ('host_entered', 'Host entered'), ('guest_entered', 'Guest entered')], max_length=20),
        ),
    ]
