# Generated by Django 4.2.15 on 2026-10-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(choices=[('deliver_admin_command', 'Deliver admin command'), ('expire_unstarted_games', 'Expire unstarted games'), ('start_scheduled_tournaments', 'Start scheduled tournaments'), ('expire_tournament_entry_deadlines', 'Expire tournament entry deadlines')], max_length=40),
        ),
    ]
