# Generated by Django 4.2.15 on 2026-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_participant_alter_participation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_players',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='tournament',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='target_points',
            field=models.PositiveSmallIntegerField(default=5, help_text='Points / games to win'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='time_control',
            field=models.CharField(choices=[('none', 'None'), ('fast', 'Fast'), ('normal', 'Normal'), ('slow', 'Slow')], default='normal', max_length=20),
        ),
    ]
