# Generated by Django 4.2.15 on 2026-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_participant_alter_participation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
