# Generated by Django 4.2.15 on 2026-08-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_fixture_auto_confirmed'),
        ('tournaments', '0004_tournament_max_players_tournament_min_players_and_more'),
    ]

    operations = [
    ]
