# Generated by Django 4.2.15 on 2026-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_prize_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('tournament_entry', 'Tournament entry'), ('tournament_refund', 'Tournament refund'), ('tournament_prize', 'Tournament prize')], max_length=32),
        ),
    ]
