# Generated by Django 4.2.15 on 2026-09-07 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0010_usercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='admin_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='admin_result',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fixture',
            name='admin_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_wins', to='tournaments.participant'),
        ),
        migrations.AddField(
            model_name='participation',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FixtureAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='tournaments.fixture')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FixtureAdminState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_state', to='tournaments.fixture')),
            ],
        ),
    ]
