# Generated by Django 4.2.15 on 2026-09-10 10:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_direct_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='directplaysettings',
            name='coin_grant_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='directplaysettings',
            name='coin_grant_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directplaysettings',
            name='coin_grant_interval_hours',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='headtoheadtable',
            name='is_quick_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('tournament_entry', 'Tournament entry'), ('tournament_refund', 'Tournament refund'), ('tournament_prize', 'Tournament prize'), ('head_to_head_entry', 'Head-to-head entry'), ('friend_game_fee', 'Friend game fee'), ('head_to_head_refund', 'Head-to-head refund'), ('head_to_head_prize', 'Head-to-head prize'), ('recurring_bonus', 'Recurring coin bonus')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='directplaysettings',
            constraint=models.CheckConstraint(check=models.Q(('coin_grant_amount__gt', 0)), name='coin_grant_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='directplaysettings',
            constraint=models.CheckConstraint(check=models.Q(('coin_grant_interval_hours__gt', 0)), name='coin_grant_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(('platform_fee_percent__gte', 8), ('platform_fee_percent__lte', 10)), name='tournament_platform_fee_percent_range'),
        ),
    ]
