# Generated by Django 4.2.15 on 2026-09-13 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0024_headtoheadtable_live_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_before', models.IntegerField()),
                ('player1_after', models.IntegerField()),
                ('player2_before', models.IntegerField()),
                ('player2_after', models.IntegerField()),
                ('source', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=32)),
                ('algorithm', models.CharField(default='elo-v1', max_length=16)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rating_result', to='tournaments.fixture')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_results_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_results_as_p2', to=settings.AUTH_USER_MODEL)),
                ('table', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rating_result', to='tournaments.headtoheadtable')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1000)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ratingresult',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('fixture__isnull', False), ('table__isnull', True)), models.Q(('fixture__isnull', True), ('table__isnull', False)), _connector='OR'), name='rating_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='ratingresult',
            constraint=models.CheckConstraint(check=models.Q(('player1', models.F('player2')), _negated=True), name='rating_distinct_players'),
        ),
        migrations.AddConstraint(
            model_name='ratingresult',
            constraint=models.CheckConstraint(check=models.Q(('winner', models.F('player1')), ('winner', models.F('player2')), _connector='OR'), name='rating_winner_is_player'),
        ),
    ]
