# Generated by Django 4.2.15 on 2026-09-19 14:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_tournament_prize_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directplaysettings',
            name='ai_game_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='kind',
            field=models.CharField(choices=[('ai_game_fee', 'AI match fee'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('tournament_entry', 'Tournament entry'), ('tournament_refund', 'Tournament refund'), ('tournament_prize', 'Tournament prize'), ('head_to_head_entry', 'Head-to-head entry'), ('friend_game_fee', 'Friend game fee'), ('head_to_head_refund', 'Head-to-head refund'), ('head_to_head_prize', 'Head-to-head prize'), ('recurring_bonus', 'Recurring coin bonus')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='directplaysettings',
            constraint=models.CheckConstraint(check=models.Q(('ai_game_fee__gte', 0)), name='ai_game_fee_nonnegative'),
        ),
    ]
