# Generated by Django 4.2.15 on 2026-09-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_usercontact_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='playable_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
