# Generated by Django 4.2.15 on 2026-09-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_fixture_playable_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='starts_at',
            field=models.DateTimeField(),
        ),
    ]
