# Generated by Django 4.2.15 on 2026-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_tournament_starts_at_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='headtoheadtable',
            name='guest_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headtoheadtable',
            name='host_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
