# Generated by Django 4.2.15 on 2026-09-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_tournament_prize_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamelink', '0004_admingamecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPlayRematch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('created', 'Created')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_table', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_from_rematch', to='tournaments.headtoheadtable')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_play_rematches_requested', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_play_rematches_received', to=settings.AUTH_USER_MODEL)),
                ('source_table', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rematch_request', to='tournaments.headtoheadtable')),
            ],
        ),
    ]
