# Generated by Django 4.2.15 on 2026-09-19 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0027_directplaysettings_ai_game_fee_and_more'),
        ('gamelink', '0005_directplayrematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('options', models.JSONField(default=dict)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_id', models.UUIDField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wallet_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.wallettransaction')),
            ],
        ),
    ]
